### ISSUE TITLE
Generate a downloadable driver with the latest updates

### ISSUE THREAD

**Issue by tzach** [scylladb/java-driver#1]
Similar to 
https://github.com/datastax/java-driver/releases

**Comment by guy9** [comment]
@haaawk I'm adding lessons to the University that use the Java driver. I'd like it to be our driver and not the Datastax one. Can you help with this issue?

**Comment by KMax** [comment]
@guy9 I can recommend a workaround which I'm going to use too. Use a repository generated by JitPack, see https://jitpack.io/#scylladb/java-driver/3.7.1-scylla-SNAPSHOT. It will use the latest code from `3.7.1-scylla` branch.

Maven:
```
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```

```
<dependency>
    <groupId>com.github.scylladb</groupId>
    <artifactId>java-driver</artifactId>
    <version>3.7.1-scylla-SNAPSHOT</version>
</dependency>
```

**Comment by KMax** [comment]
Oh, I'm sorry this approach doesn't work actually. Because the group and artifact names aren't aligned with the name of the Github repository.

Maven:
```
[ERROR] Failed to execute goal on project sail: Could not resolve dependencies for project cc.datafabric.scyllardf:sail:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.github.scylladb.java-driver:cassandra-driver-extras:bundle:3.7.1-scylla-SNAPSHOT, com.github.scylladb.java-driver:cassandra-driver-mapping:bundle:3.7.1-scylla-SNAPSHOT: Failure to find com.github.scylladb.java-driver:cassandra-driver-extras:bundle:3.7.1-scylla-3.5.1-g0f8997d-111 in https://jitpack.io was cached in the local repository, resolution will not be reattempted until the update interval of jitpack.io has elapsed or updates are forced -> [Help 1]
```

**Comment by haaawk** [comment]
@guy9 sorry for a late reply.

Our java driver has been published to Maven Central repository.
It can be accessed here: https://repo1.maven.org/maven2/com/scylladb/

Anyone can also use it by adding the following dependency to their pom.xml:
```
<dependency>
  <groupId>com.scylladb</groupId>
  <artifactId>scylla-driver-core</artifactId>
  <version>3.7.1-scylla-0</version>
</dependency>
```

or using a similar method for Ant, Gradle or SBT.
