### ISSUE TITLE
Endpoint of contactPoint should be replaced with broadcast address.

### ISSUE THREAD

**Issue by congguosn** [scylladb/java-driver#108]
If a proxy is used as the contact point, it will be treated as the member of scylla backend replicas, but actually it is not.

For example, if a cloud load balancer is used as contact point, client will send part of the data traffic to it, but actually the traffic should go to the broadcast address get from system.local.

**Comment by haaawk** [comment]
I'm trying to understand your use case. Why are you using cloud load balancer instead of nodes in the cluster, @congguosn ? How do you intend to read system.local on the first place if you don't point the driver to a real Scylla node?

**Comment by roydahan** [comment]
Closing as non responsive.
