### ISSUE TITLE
Need releases of version spark-connector uses to make it shard aware

### ISSUE THREAD

**Issue by tarzanek** [scylladb/java-driver#121]
Hi guys

can you please release shard aware
4.12.0  (spark connector 3.1)

4.10.0 (spark connector 3.0.1)

?

tia
Lubos

**Comment by tarzanek** [comment]
(continuation of https://github.com/scylladb/java-driver/issues/58 )

**Comment by avelanarius** [comment]
4.10.0.0 branch: https://github.com/scylladb/java-driver/tree/scylla-4.10.0.x (will release today), passes unit/integration tests (with Cassandra)
4.12.0.0 branch: in-progress

**Comment by avelanarius** [comment]
4.12.0.0 branch: https://github.com/scylladb/java-driver/tree/scylla-4.12.0.x

Both 4.10.0.0 and 4.12.0.0 branches pass unit/integration tests (with Cassandra). I'll do some final manual testing and release it.

**Comment by avelanarius** [comment]
4.12.0.0 is now released: https://repo1.maven.org/maven2/com/scylladb/java-driver-core/4.12.0.0/

**Comment by avelanarius** [comment]
@tarzanek 4.10.0.0 is released too: https://repo1.maven.org/maven2/com/scylladb/java-driver-core/4.10.0.0/
