### ISSUE TITLE
Update CONTRIBUTING.md (and others) with info helping new driver developers

### ISSUE THREAD

**Issue by avelanarius** [scylladb/java-driver#130]
As correctly suggested by @Lorak-mmk (https://github.com/scylladb/java-driver/pull/122#issuecomment-1109791656), `CONTRIBUTING.md` (and other similar files) should be updated with the info on how to run integration tests. More broadly, those files could contain more information about what our release process looks like (currently it's stored in a wiki on a private scylladb repository). Any misleading information that doesn't apply to our fork (but only to upstream DataStax repository) should be removed from the documentation (example: #104).

**Comment by avelanarius** [comment]
@Bouncheck as we previously talked, please do this part: "CONTRIBUTING.md (and other similar files) should be updated with the info on how to run integration tests".

**Comment by Bouncheck** [comment]
I've left most of the stuff as is and changed what I know about so far. If anyone stumbles upon something not relevant please leave a comment
