### ISSUE TITLE
Add 4.14, 4.15 support

### ISSUE THREAD

**Issue by racevedoo** [scylladb/java-driver#131]
Currently the most recent release in the 4.x branch is 4.13. Datastax recently released 4.14 with some improvements and security patches.

Are there any plans to merge this release into scylla driver? Thanks in advance!

**Comment by racevedoo** [comment]
Datastax changelog for 4.14: https://github.com/datastax/java-driver/blob/4.x/changelog/README.md

**Comment by mykaul** [comment]
I think this has been completed already. @avelanarius ?

**Comment by racevedoo** [comment]
Yep, it's done ([ref](https://mvnrepository.com/artifact/com.scylladb/java-driver-core)). Closing
