### ISSUE TITLE
Host Sharding information is initialized per host on initial control connection setup - not allowing to change availability information from server end

### ISSUE THREAD

**Issue by slivne** [scylladb/java-driver#14]
Host Sharding Info is set on first connection setup when the first SUPPORTED response is received 

https://github.com/scylladb/java-driver/blob/3.7.1-scylla/driver-core/src/main/java/com/datastax/driver/core/Connection.java#L404

Following that the HostConnectionPool will assume that sharding for the host was set and thus should be used. 

This does not allow to change sharding information availability (enable/disable) without redeploying applications. 

In case sharding information is disabled the state is more severe as the HostConnectionPool will assume sharding information should exist and will attempt to backfill the connection with sharding information - although the server will not respond with that ( cuasing connections to be setup and tear down over and over).

We should allow switching freely per host between the two modes

**Comment by avnerbarr** [comment]
@slivne is this deployed to maven? please provide information so that we can go ahead and deploy

**Comment by haaawk** [comment]
@avnerbarr yes - it's on maven. Artifact version 3.7.1-scylla-1.
