### ISSUE TITLE
Export findbugs packages in OSGI

### ISSUE THREAD

**Issue by manaldush** [scylladb/java-driver#149]
osgi.wiring.package; (&(osgi.wiring.package=com.datastax.oss.driver.api.core)(version>=4.14.0)(!(version>=5.0.0))) [caused by: Unable to resolve 415.0: missing requirement [415.0] osgi.wiring.package; (&(osgi.wiring.package=javax.annotation)(version>=3.0.0)(!(version>=4.0.0)))]

Do we really need to have testing tool dependency as import package in META-INF?

**Comment by Bouncheck** [comment]
I've assumed it's about 4.x version of the driver based on the package names.
I've just made a quick change that results in javax.annotation gone from MANIFEST.MF in core subdirectory.
It still is present in shaded version though (I'll look into if that can be reduced too or not).
Does that resolve this issue?
