### ISSUE TITLE
Question: Is there any possibility to add a JDBC driver for scylladb?

### ISSUE THREAD

**Issue by ghevge** [scylladb/java-driver#150]
Hi,

I'm very new to scylladb, stumbled over it 2 days ago, while looking for a high performance DB, so I don't know all the ins and outs of this product.
I'm planning to write a new app, but which I don't want to tightly couple the with this DB way of writing code. Instead, if possible, I would like to use a java persistence framework like mybatis. But for mybatis to work it will require a decent JDBC driver. Though my question:

Is there any possibility to add a JDBC driver for scylladb?

Thanks

**Comment by Bouncheck** [comment]
Unfortunately there are no plans to and no work is being done on that.
JDBC does not really fit with Scylla in general. It's good for SQL databases but in case of NoSQL every solution tends to be different. Implementing JDBC API with CQL underneath will probably result in suboptimal performance somewhere.
However if you still want to go ahead with JDBC solution you can take a look for example at [this wrapper](https://github.com/ing-bank/cassandra-jdbc-wrapper). You can replace driver dependency in pom.xml with:
```
<dependency>
    <groupId>com.scylladb</groupId>
    <artifactId>java-driver-core</artifactId>
    <version>4.14.1.0</version>
</dependency>
```
This way you can use Scylla java driver with JDBC API.
Keep in mind this is not something that has been tested and this project does not belong to ScyllaDB so there are no guarantees or assumed responsibility.
