### ISSUE TITLE
Add support for `USING TIMEOUT` and `BYPASS CACHE` in query builders.

### ISSUE THREAD

**Issue by shawjef3** [scylladb/java-driver#155]
`USING TIMEOUT` is for `SELECT`, `UPDATE`, and `INSERT` statements, and was added in 4.4. It takes a CqlDuration when used with a bind marker. https://docs.scylladb.com/stable/cql/dml.html#using-timeout

`BYPASS CACHE` is for `SELECT` statements. It was added in 3.1. https://docs.scylladb.com/stable/cql/dml.html#bypass-cache

**Comment by shawjef3** [comment]
Implemented by https://github.com/scylladb/java-driver/pull/156.

**Comment by tarzanek** [comment]
this can likely be fixed after someone verifies the PR works @avelanarius 
or we can close by default? (in this case it is kinda straightforward)

**Comment by shawjef3** [comment]
@tarzanek yes we can close this. Just it needs to be released
