### ISSUE TITLE
Add a Copyright to footer

### ISSUE THREAD

**Issue by tzach** [scylladb/java-driver#165]
### Problem
The Scylla Java driver is a fork of Datastax driver
https://github.com/datastax/java-driver

Altgho the Scylla Driver project HP include the Datastax Copyright and Apache Licence[1], it would be better to include it in *all* pages froked from the original Datastax driver, even if it was updated.

###  Suggest a fix
Include the following in the footer of every page:

The ScyllaDB Java Driver is a fork of [Datastax Java Driver for Apache Cassandra](https://github.com/datastax/java-driver).
See license and copyright [here](https://java-driver.docs.scylladb.com/stable/index.html#license).

[1] https://java-driver.docs.scylladb.com/stable/index.html#license

**Comment by tzach** [comment]
@dgarcia360 how can we update the footer of this project (not the global theme)?

**Comment by Bouncheck** [comment]
Closing as completed by #196
