### ISSUE TITLE
DAO - BYPASS CACHE and USING TIMEOUT capabilities

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/java-driver#168]
As of commits https://github.com/scylladb/java-driver/commit/d184387961cc439b2c9379d90868fe7b75ad2284 and https://github.com/scylladb/java-driver/commit/d2c151331a1d1fd29c12f678f16bb66974e8aa0d, it would be nice to cut off a driver release with such capabilities.

We have users asking for it and, nonetheless, these commits are great to make use of ScyllaDB specific CQL extensions, thus a differentiator for our users.

@avelanarius

**Comment by mykaul** [comment]
@avelanarius - I assume it's waiting for other content to get in (topology, etc.) ?

**Comment by avelanarius** [comment]
4.15.0.0 is released and has those commits. However, those changes were made only in `QueryBuilder` and it looks like the same changes should also be done in `Mapper/DAO` components of the driver.

**Comment by mykaul** [comment]
@avelanarius  - following a question from Support - what's the status of the above mentioned needed change?

**Comment by mykaul** [comment]
@avelanarius - ping

**Comment by mykaul** [comment]
@avelanarius , @roydahan - ping

**Comment by roydahan** [comment]
It was part of Sprint 2 "Todos" as P2, but I don't think @Bouncheck has reached that.
AFAIK he still works on his P1's.

**Comment by mykaul** [comment]
@Bouncheck - in which release is it?

**Comment by Bouncheck** [comment]
Should be available in 4.17.0.1
