### ISSUE TITLE
Can't set limit field in BoundStatementBuilder

### ISSUE THREAD

**Issue by manaldush** [scylladb/java-driver#207]
Installation details
Scylla version (or git commit hash): 5.1.5
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

As client we are using scylla java driver ver 4.14.1.0
We have next prepared statement in our code

    _selectWithLimit = this.session.prepare(
            selectFrom("some_table")
                    .columns(columns())
                    .where(
                            eqClause("id"),
                            eqClause("some_date"),
                            greaterOrEqualClause("some_date_2"),
                            lesserOrEqualClause("some_date_2"))
                    .limit(bindMarker())
                    .asCql()).bind();_
and then when we try to build statement and to set the limit field with code

    _BoundStatementBuilder statement = new BoundStatementBuilder(selectWithLimit );
    .....
    setInt(statement, 0, id);
    setDateAsLong(statement, 1, some_date);
    setDateAsLong(statement, 2, some_date_lower);
    setDateAsLong(statement, 3, some_date_upper);
    setInt(statement, 4, limit);_
we got exception

java.lang.ArrayIndexOutOfBoundsException: 4
at com.datastax.oss.driver.api.core.cql.BoundStatementBuilder.setBytesUnsafe(BoundStatementBuilder.java:149) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
at com.datastax.oss.driver.api.core.cql.BoundStatementBuilder.setBytesUnsafe(BoundStatementBuilder.java:39) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
at com.datastax.oss.driver.api.core.data.SettableByIndex.set(SettableByIndex.java:94) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]

Before we used scylla ver 5.0.9 and it was ok.

**Comment by Gor027** [comment]
According to the stack trace, the values for bound variables are set using `BoundStatementBuilder.setBytesUnsafe`, perhaps a typed setter should be used instead to pass a higher-level Java representation.
I can try to reproduce the issue with Scylla version 5.0.9, but please provide a full code example instead of a pseudocode.

**Comment by manaldush** [comment]
I've wrote some synthetic code for reproducing this error. You can use it. 
With this code you can reproduce error with scylla 5.1.5 and check that it is fine on 5.0.9
CQL for creating test table in scylla


CREATE TABLE quotacache_vt6.test_table (
    id int,
    type int,
    created_dtm timestamp,
    data text,
    PRIMARY KEY ((id, type), created_dtm)
) WITH read_repair_chance = 0.0
    AND dclocal_read_repair_chance = 0.1
    AND gc_grace_seconds = 864000
    AND bloom_filter_fp_chance = 0.01
    AND caching = { 'keys' : 'ALL', 'rows_per_partition' : 'NONE' }
    AND comment = ''
    AND compaction = { 'class' : 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold' : 32, 'min_threshold' : 4, 'tombstone_compaction_interval' : 864000 }
    AND compression = { 'chunk_length_in_kb' : 64, 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor' }
    AND default_time_to_live = 0
    AND speculative_retry = '99PERCENTILE'
    AND min_index_interval = 128
    AND max_index_interval = 2048
    AND crc_check_chance = 1.0
    AND cdc = {'enabled':'false'};


Java code

    void getTestData(long lowerTimePeriodBoundary, long upperTimePeriodBoundary) {

        BoundStatement selectTestTable = this.session.prepare(
                selectFrom("test_table")
                        .columns(new String[]{"id", "type", "created_dtm", "data"})
                        .where(
                                eqClause("id"),
                                eqClause("type"),
                                greaterOrEqualClause("created_dtm"),
                                lesserOrEqualClause("created_dtm"))
                        .limit(bindMarker())
                        .asCql()).bind();

        BoundStatementBuilder statement = new BoundStatementBuilder(selectTestTable);
        statement.set(0, 1, TypeCodecs.INT);
        statement.set(1, 2, TypeCodecs.INT);
        statement.set(2, (lowerTimePeriodBoundary == 0) ? null : Instant.ofEpochMilli(lowerTimePeriodBoundary), TypeCodecs.TIMESTAMP);
        statement.set(3, (upperTimePeriodBoundary == 0) ? null : Instant.ofEpochMilli(upperTimePeriodBoundary), TypeCodecs.TIMESTAMP);
        statement.set(4, 5000, TypeCodecs.INT);
        session.execute(statement.build()).all();
    }


stack trace

java.lang.ArrayIndexOutOfBoundsException: 4
	at com.datastax.oss.driver.api.core.cql.BoundStatementBuilder.setBytesUnsafe(BoundStatementBuilder.java:149) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
	at com.datastax.oss.driver.api.core.cql.BoundStatementBuilder.setBytesUnsafe(BoundStatementBuilder.java:39) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
	at com.datastax.oss.driver.api.core.data.SettableByIndex.set(SettableByIndex.java:94) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
	at XXXXXXXXXXXX.getTestData(ScyllaTestClass.java:226) ~[XXXXXXXXXXXX]

**Comment by manaldush** [comment]
I've wrote some synthetic code for reproducing this error. You can use it.
With this code you can reproduce error with scylla 5.1.5 and check that it is fine on 5.0.9
CQL for creating test table in scylla

CREATE TABLE quotacache_vt6.test_table (
id int,
type int,
created_dtm timestamp,
data text,
PRIMARY KEY ((id, type), created_dtm)
) WITH read_repair_chance = 0.0
AND dclocal_read_repair_chance = 0.1
AND gc_grace_seconds = 864000
AND bloom_filter_fp_chance = 0.01
AND caching = { 'keys' : 'ALL', 'rows_per_partition' : 'NONE' }
AND comment = ''
AND compaction = { 'class' : 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold' : 32, 'min_threshold' : 4, 'tombstone_compaction_interval' : 864000 }
AND compression = { 'chunk_length_in_kb' : 64, 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor' }
AND default_time_to_live = 0
AND speculative_retry = '99PERCENTILE'
AND min_index_interval = 128
AND max_index_interval = 2048
AND crc_check_chance = 1.0
AND cdc = {'enabled':'false'};

Java code

package com.scylla.test;

import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.core.cql.BoundStatement;
import com.datastax.oss.driver.api.core.cql.BoundStatementBuilder;
import com.datastax.oss.driver.api.core.type.codec.TypeCodecs;
import com.datastax.oss.driver.api.querybuilder.relation.Relation;

import java.time.Instant;

import static com.datastax.oss.driver.api.querybuilder.QueryBuilder.bindMarker;
import static com.datastax.oss.driver.api.querybuilder.QueryBuilder.selectFrom;

import static java.util.Objects.requireNonNull;

public class ScyllaTestClass {
    private final BoundStatement selectTestTable;
    private final CqlSession session;

    public ScyllaTestClass(CqlSession session) {
        this.session = session;
        selectTestTable = session.prepare(
                selectFrom("test_table")
                        .columns(new String[]{"id", "type", "created_dtm", "data"})
                        .where(
                                eqClause("id"),
                                eqClause("type"),
                                greaterOrEqualClause("created_dtm"),
                                lesserOrEqualClause("created_dtm"))
                        .limit(bindMarker())
                        .asCql()).bind();
    }


    void getTestData(long lowerTimePeriodBoundary, long upperTimePeriodBoundary) {

        BoundStatementBuilder statement = new BoundStatementBuilder(selectTestTable);
        statement.set(0, 1, TypeCodecs.INT);
        statement.set(1, 2, TypeCodecs.INT);
        statement.set(2, (lowerTimePeriodBoundary == 0) ? null : Instant.ofEpochMilli(lowerTimePeriodBoundary), TypeCodecs.TIMESTAMP);
        statement.set(3, (upperTimePeriodBoundary == 0) ? null : Instant.ofEpochMilli(upperTimePeriodBoundary), TypeCodecs.TIMESTAMP);
        statement.set(4, 5000, TypeCodecs.INT);
        session.execute(statement.build()).all();
    }

    static Relation eqClause(String column) {
        return Relation.column(requireNonNull(column)).isEqualTo(bindMarker(column));
    }

    static Relation greaterOrEqualClause(String column) {
        return Relation.column(requireNonNull(column)).isGreaterThanOrEqualTo(bindMarker(column));
    }

    static Relation lesserOrEqualClause(String column) {
        return Relation.column(requireNonNull(column)).isLessThanOrEqualTo(bindMarker(column));
    }
}


stack trace attached

java.lang.ArrayIndexOutOfBoundsException: 4
	at com.datastax.oss.driver.api.core.cql.BoundStatementBuilder.setBytesUnsafe(BoundStatementBuilder.java:149) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
	at com.datastax.oss.driver.api.core.cql.BoundStatementBuilder.setBytesUnsafe(BoundStatementBuilder.java:39) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
	at com.datastax.oss.driver.api.core.data.SettableByIndex.set(SettableByIndex.java:94) ~[scylla-driver-holder-2.5.1.0-SNAPSHOT.jar:2.5.1.0-SNAPSHOT]
	at com.scylla.test.ScyllaTestClass.getTestData(ScyllaTestClass.java:42)
	
stack trace points to line
statement.set(4, 5000, TypeCodecs.INT);

**Comment by Gor027** [comment]
Thanks for the full code example, it helped to reproduce and find the important details missing in the previous example. There are two problems with the usage of bind markers that caused the exception:
* the same named bind marker `created_dtm` represents different values: upper and lower timestamps. Starting from version 5.1, Scylla treats it as a single variable, [see here](https://github.com/scylladb/scylladb/issues/10810).
* It is not a good practice to mix named and unnamed bind markers even though preparing such a request is allowed. This may potentially cause some trouble, [see here](https://github.com/scylladb/scylladb/issues/12732)

A quick and simple fix for the above code example would be to not pass the `column` parameter while creating bind markers in `eqClause`, `greaterOrEqualClause` and `lesserOrEqualClause` functions. Anyway, you set the values by index and not by name, so named bind markers are redundant here. Hope this will help you.

**Comment by avelanarius** [comment]
Refs https://github.com/scylladb/scylladb/issues/11945 (another issue in Scylla Core describing the problem and why we decided on this behavior)
