### ISSUE TITLE
3.10.2-scylla-1 / 3.7.1-scylla-2 failing tests

### ISSUE THREAD

**Issue by fruch** [scylladb/java-driver#214]
3 test are failing consistently on the java-driver-matrix runs

* com.datastax.driver.core.SessionLeakTest.connectionLeakTest
* com.datastax.driver.core.PoolingOptionsIntegrationTest.should_be_able_to_use_custom_initialization_executor
* com.datastax.driver.core.ClusterStressTest.clusters_should_not_leak_connections

https://jenkins.scylladb.com/job/scylla-master/job/driver-tests/job/java-driver-matrix-test/993

**Comment by roydahan** [comment]
Closing as these may be obsolete by now.
Maintainer of java-matrix will open new ones for failing tests.
