### ISSUE TITLE
TokenRange.mergeWith incorrectly handles ranges with the same start

### ISSUE THREAD

**Issue by RadoBuransky** [scylladb/java-driver#216]
https://github.com/scylladb/java-driver/blob/b3f3ebaf161b21e5c4840ec294595d4e4b39d9bf/driver-core/src/main/java/com/datastax/driver/core/TokenRange.java#L293

I would expect that if I merge ]A,B] with ]A,C] where C>B then I get ]A,C] and not the full ring.

**Comment by avelanarius** [comment]
I'm assuming that Scylla/Cassandra wouldn't return such ranges, so closing this as won't fix.
