### ISSUE TITLE
SELECT_LOCAL frequency

### ISSUE THREAD

**Issue by tarzanek** [scylladb/java-driver#23]
A client using the driver seems to do too frequents queries with SELECT_LOCAL
(we see 600 OPS coming every second)

https://github.com/scylladb/java-driver/blob/9ab00c44621727531e639e03f43cf57783e5c1a4/driver-core/src/main/java/com/datastax/driver/core/ControlConnection.java#L73

so the big Q is how many times should this query be seen, if we want to cache it for some time, etc. to avoid constant querying of the cluster

**Comment by tarzanek** [comment]
So was there some round robin approach to make the scylla recieve above query on different shards/nodes? @haaawk any chance you remember such patch?

**Comment by haaawk** [comment]
There was no round robin improvement. The fix was to add WHERE key='local' so that the query is handled on a single node (single key query) and does not do full cluster scan.

**Comment by tarzanek** [comment]
the client is Spring 2.0.0 + our shard aware driver 3.7.1 build 2 (versus original 3.4 of cassandra)
note that I tried Spring 2.2.4 (which integrates 3.7.1 cassandra) with our shard aware driver and haven't seen such behaviour

**Comment by slivne** [comment]
`system.local` is a local table existing on every node,

this is probably their mechanism to check that they can send queries.

I don't understand what the the problem ?

If they do `select * from system.local` - this will do a full scan on a local node (all shards on one node)

if they do `select * from system.local where key=local` this will be a single partition query on the local node.


Please clarify whats the problem/issue

**Comment by haaawk** [comment]
@tarzanek Could you please say what was the problem? Surely not those 600 single partition queries to local table?

**Comment by tarzanek** [comment]
we are not sure, fwiw these ghost queries were gone upon clients hosted k8s were restarted, so it looks like leftover clients, I think this bug can be closed
