### ISSUE TITLE
[4.x] Compilation warnings when annotating `@Entity` record's fields with exclusive annotations

### ISSUE THREAD

**Issue by muzarski** [scylladb/java-driver#246]
Java 14 introduces `record` keyword which stands for immutable data class. Records require only the name and types of fields. Java generates some code to operate on the record's objects - including public getter methods.

When annotating record with `@Entity` annotation, its field with one of the [exclusive](https://github.com/scylladb/java-driver/blob/4.x/mapper-processor/src/main/java/com/datastax/oss/driver/internal/mapper/processor/entity/DefaultEntityFactory.java#L69-L71) annotations, we get a compilation warning.

Simple example:
```Java
@Entity
public record FooRecord(
	@PartitionKey int fooPK,
	@ClusteringColumn String fooCC
) { }
```
We get following compilation warnings:
```
/home/mikolajuzarski/playground/java-driver-test/src/main/java/org/example/FooRecord.java:9:27
java: [FooRecord.fooPK] @PartitionKey should be used either on the field or the getter, but not both. The annotation on this field will be ignored.

/home/mikolajuzarski/playground/java-driver-test/src/main/java/org/example/FooRecord.java:10:34
java: [FooRecord.fooCC] @ClusteringColumn should be used either on the field or the getter, but not both. The annotation on this field will be ignored.
```

The specific version of java-driver (and mapper-processor) used in the snippet is `4.14.1.0`, but from what I've seen in the code, the same logic applies to all of `4.x` versions.

It seems like Java duplicates the field annotation to its generated getter method as well. We could make an exception for records, so we don't generate such warnings for their fields. There is already some code for handling record `@Entity` structures in `mapper-processor` module. For example, see this [hack](https://github.com/scylladb/java-driver/blob/4.x/mapper-processor/src/main/java/com/datastax/oss/driver/internal/mapper/processor/MapperProcessor.java#L116-L120).

**Comment by roydahan** [comment]
BTW, The same issue also exist for the upstream driver - https://datastax-oss.atlassian.net/browse/JAVA-3006

**Comment by roydahan** [comment]
PR is pending review - https://github.com/scylladb/java-driver/pull/251
