### ISSUE TITLE
Wrong handling of multiple consecutive empty pages in Java Driver 4.x

### ISSUE THREAD

**Issue by avelanarius** [scylladb/java-driver#254]
When Scylla returns multiple consecutive empty pages, Java Driver 4.x doesn't handle it correctly. Reproducer:
```java
CqlSession cqlSession = CqlSession.builder()
        .addContactPoint(InetSocketAddress.createUnresolved("127.0.0.2", 9042))
        .withLocalDatacenter("datacenter1").build();

cqlSession.execute("CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': 1}");

cqlSession.execute("CREATE TABLE IF NOT EXISTS ks.t (pk int, ck int, v int, PRIMARY KEY(pk, ck))");

for (int i = 0; i < 50; i++) {
    System.out.println("Insert " + i);
    cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", i, i, 15);
    cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", i, i, 32);
}

cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", 8, 8, 14);
cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", 11, 11, 14);
cqlSession.execute("INSERT INTO ks.t(pk, ck, v) VALUES (?, ?, ?)", 14, 14, 14);

SimpleStatement st = SimpleStatement.newInstance("SELECT * FROM ks.t WHERE v = 14 ALLOW FILTERING");
st = st.setPageSize(1);

cqlSession.execute(st).all().forEach(r -> {
    System.out.println(r);
});
cqlSession.close();
```

The code is supposed to print 3 rows, but it doesn't print anything.

**Comment by avelanarius** [comment]
Maybe this is a wrong repo to write this, but as for other drivers:

- Rust Driver does not have this problem.
- Java Driver 3.x does not have this problem.

**Comment by vladzcloudius** [comment]
First of all I'm not sure the "expected behavior" is correct: you set the page size to 1 and execute the query just once. AFAIR this way you are supposed to get a single page only.
And as such you should be getting a single row at most. Don't you?

If I'm right then the behavior of the 4.x driver is actually right (it apparently brings you a single empty page) while the behavior of other drivers isn't.

Or possibly the semantics of `execute()` got changed between drivers and Java driver versions: 
* It 4.x it brings you a single page.
* In 3.x and in Rust - brings you all pages (which is kinda weird and seems bogus).

**Comment by avelanarius** [comment]
> First of all I'm not sure the "expected behavior" is correct: you set the page size to 1 and execute the query just once. AFAIR this way you are supposed to get a single page only. And as such you should be getting a single row at most. Don't you?

No, the driver is supposed to transparently fetch new pages as you iterate (https://docs.datastax.com/en/developer/java-driver/4.13/manual/core/paging/#quick-overview).

**Comment by vladzcloudius** [comment]
> > First of all I'm not sure the "expected behavior" is correct: you set the page size to 1 and execute the query just once. AFAIR this way you are supposed to get a single page only. And as such you should be getting a single row at most. Don't you?
> 
> No, the driver is supposed to transparently fetch new pages as you iterate (https://docs.datastax.com/en/developer/java-driver/4.13/manual/core/paging/#quick-overview).

Got it. Then there is some bug indeed. 
I remembered that you needed some combo of `hasMorePages(...)` and `execute()` in a loop to fetch results. But I see that they hid these in the iterator these days.
Thanks for explaining.

**Comment by roydahan** [comment]
@avelanarius are you sending a PR with the fix (https://github.com/avelanarius/java-driver/commit/40da47a784fe1fa2b77a384587976e857513ea9b)?
(Unless you already did and I missed it.

**Comment by sylwiaszunejko** [comment]
Update about other drivers: 
* Python Driver does not have this problem.
* gocql does not have this problem.

**Comment by mykaul** [comment]
> * gocql does have this problem.

Thanks @sylwiaszunejko - please open an issue on its repo so we can track it properly.

**Comment by sylwiaszunejko** [comment]
> > * gocql does have this problem.
> 
> Thanks @sylwiaszunejko - please open an issue on its repo so we can track it properly.

Sorry for my mistake, I already edited the comment it does not have this problem

**Comment by mykaul** [comment]
> > > * gocql does have this problem.
> > 
> > 
> > Thanks @sylwiaszunejko - please open an issue on its repo so we can track it properly.
> 
> Sorry for my mistake, I already edited the comment it does not have this problem

Even better! So now lets just make sure Rust and Java are safe (and btw, would be good to add tests to them)

**Comment by roydahan** [comment]
@avelanarius are we sending PR to the upstream driver? to our fork? Both?

**Comment by mykaul** [comment]
@avelanarius - what's the latest status here?

**Comment by avelanarius** [comment]
Solved by merged https://github.com/scylladb/java-driver/commit/a04fadf25fcfaefb818817f93407f5cfa484d993
