### ISSUE TITLE
Implement support for CDC partitioner

### ISSUE THREAD

**Issue by haaawk** [scylladb/java-driver#26]
CDC Log uses custom partitioner so if we want to use TokenAwareLoadBalancingPolicy we have to make the driver aware of the CDC partitioner.

**Comment by avelanarius** [comment]
Implemented a long time ago in both `3.x` (5e8ce09f1de01b8d33ec76a3379081bac7127690) and `4.x` (7b6182aebcff249e9ac6dcacc29f43fb6070bae5) branches. I should have known to put "Fixes ..." in the commit messages...
