### ISSUE TITLE
Update driver to populate tablet metadata for request routing (4.x only)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/java-driver#268]
Derived from [Tablets implementation plan](https://docs.google.com/document/d/1KTik_5FyyN1eo4wAw9jrmGaT5cAuNn_TiiuLiJhmsmE/edit)

@tgrabiec please fill-in the details of this task

**Comment by tgrabiec** [comment]
The task is to update routing information based on feedback from the server returned in `custom_payload` field of the response, as documented in this PR: https://github.com/scylladb/scylladb/pull/16148

**Comment by roydahan** [comment]
@Bouncheck please close if done.

**Comment by Bouncheck** [comment]
Closing as completed by #241
