### ISSUE TITLE
Change repository default branch to a proper "Scylla" version

### ISSUE THREAD

**Issue by felipegasparini** [scylladb/java-driver#27]
Currently the default branch in this Github repository is set to https://github.com/scylladb/java-driver/tree/3.x . This version has no customizations from Scylla and the README and remaining documentation only has references to the Datastax driver.

![image](https://user-images.githubusercontent.com/2293568/84945670-d5419380-b0e7-11ea-9c3c-a19c832a0296.png)
The image above shows that the default instructions to get the driver from Maven are refering to the Datastax version.

It would be awesome for users if the default branch was set to a real Scylla version of this driver, so any user opening this Github repository would find imediatelly documentation and instructions for the Scylla version.

![image](https://user-images.githubusercontent.com/2293568/84945913-2b163b80-b0e8-11ea-8d6b-f07411321f06.png)
The image above shows the instructions from one of the "scylla" branches correctly giving instructions of how to get the Scylla driver from Maven. This should be the default one.

**Comment by haaawk** [comment]
The instruction how to change default branch can be found here:
https://help.github.com/en/github/administering-a-repository/setting-the-default-branch

@avikivity I don't see the "Settings" tab in this repository. Could it be that I don't have the necessary permissions?

**Comment by avikivity** [comment]
@haaawk I increased your permissions level, please check again.

**Comment by haaawk** [comment]
@avikivity nope. Now I see "Settings" tab but it has only "Moderation" and "Interaction limits" sections. No "Branches" section.

![image](https://user-images.githubusercontent.com/1311149/85030721-16848280-b17e-11ea-883d-385ae1722fde.png)

**Comment by haaawk** [comment]
Fixed.
