### ISSUE TITLE
 Prevent reusing cached cancelled requests #1757  from apache cassandra driver

### ISSUE THREAD

**Issue by zooptwopointone** [scylladb/java-driver#272]
I ran into this bug after upgrading Spring boot and probably more likely reactor.   which caused our app to get cancellations.    I can confirm the problem exists exactly where it is stated here using ZIPs in the flow.

I have compiled and used this driver's patch and works without issue.  I have put a comment on the JIRA for the apache side.  But was hoping that Scylla could introduce a fix faster.  As I do use the Scylla driver.

Thank you.

https://github.com/apache/cassandra-java-driver/pull/1757

**Comment by roydahan** [comment]
This should for the upstream decision and will be updated once we merge from upstream.
