### ISSUE TITLE
Change default branch

### ISSUE THREAD

**Issue by dgarcia360** [scylladb/java-driver#28]
I am automating the docs generation to match the main docs style with Sphinx and GitHub Actions. To be able to enable multi version support, I'd need this repository to have a default development branch named "master" or "latest" as the default one instead of a branch pointing to a specific version (3.7.1-scylla).  Thank you very much! 

cc/ @tzach @lauranovich

![image](https://user-images.githubusercontent.com/9107969/89159363-aab07a80-d56f-11ea-88d4-5c3a2879f624.png)

**Comment by haaawk** [comment]
master is impossible. We can think about "latest".

**Comment by haaawk** [comment]
Done. "latest" is now the default branch.

**Comment by dgarcia360** [comment]
Thanks!
