### ISSUE TITLE
4.x: Decouple schema fetch queries from server-side timeouts

### ISSUE THREAD

**Issue by roydahan** [scylladb/java-driver#298]
See https://github.com/scylladb/scylla-drivers/issues/4

Migrated to Jira: [DRIVER-193](https://scylladb.atlassian.net/browse/DRIVER-193)

[DRIVER-193]: https://scylladb.atlassian.net/browse/DRIVER-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by roydahan** [comment]
@Bouncheck & @avelanarius please try to look into it this week and provide an ETA.
If you think it's something small enough to pull into our current sprint, please do.

**Comment by roydahan** [comment]
current ETA is Jun 19th (end of current sprint).

**Comment by mykaul** [comment]
> current ETA is Jun 19th (end of current sprint).

Updated - end of June.

**Comment by mykaul** [comment]
@Bouncheck - isn't this fixed via https://github.com/scylladb/java-driver/pull/312 and can be closed?

**Comment by Bouncheck** [comment]
Yes, that's correct.
