### ISSUE TITLE
No release notes for the 4.18.0 release

### ISSUE THREAD

**Issue by mykaul** [scylladb/java-driver#311]
Couldn't find anything anywhere. Looked at:
- https://github.com/scylladb/java-driver/releases/tag/4.18.0.0
- https://forum.scylladb.com/c/scylladb-release-notes/18
- https://opensource.docs.scylladb.com/stable/using-scylla/drivers/cql-drivers/scylla-java-driver
- https://java-driver.docs.scylladb.com/stable/

CC @roydahan , @tzach

**Comment by roydahan** [comment]
Where do we publish the release notes in general?

@Bouncheck maybe we should start creating also "releases" not only tags and start publishing release notes over there like we do in other drivers.

**Comment by Bouncheck** [comment]
I haven't heard of established practice about release notes in case of java driver, I'll search for some and I'll try to follow suit.
Github releases is also something we can start doing.

**Comment by roydahan** [comment]
I think that the GitHub releases should be the right place.
We can also add some automation around it and before publishing the release just to give it a human touch.

**Comment by mykaul** [comment]
> I haven't heard of established practice about release notes in case of java driver, I'll search for some and I'll try to follow suit. Github releases is also something we can start doing.

If you released it and no one heard about it, did you actually release it?
And BTW, https://java-driver.docs.scylladb.com/stable/changelog/index.html has an (outdated) changelog.

**Comment by Lorak-mmk** [comment]
> > I haven't heard of established practice about release notes in case of java driver, I'll search for some and I'll try to follow suit. Github releases is also something we can start doing.
> 
> If you released it and no one heard about it, did you actually release it? And BTW, https://java-driver.docs.scylladb.com/stable/changelog/index.html has an (outdated) changelog.

This is probably changelog from upstream, so it does not include our changes

**Comment by mykaul** [comment]
> > > I haven't heard of established practice about release notes in case of java driver, I'll search for some and I'll try to follow suit. Github releases is also something we can start doing.
> > 
> > 
> > If you released it and no one heard about it, did you actually release it? And BTW, https://java-driver.docs.scylladb.com/stable/changelog/index.html has an (outdated) changelog.
> 
> This is probably changelog from upstream, so it does not include our changes

I know.

**Comment by mykaul** [comment]
We've improved with 4.18.0.1 - but it's not in the forum yet!

**Comment by roydahan** [comment]
4.18.0.1 also has release notes.
The forum is a manual process.
@Bouncheck please update the scylladb community forum, closing this one.
