### ISSUE TITLE
Question - What is the latest release?

### ISSUE THREAD

**Issue by kharmabum** [scylladb/java-driver#33]
Quick question.

My company currently utilizes the 4.2.0 version of the Datastax driver. We'd like to test the scylla driver and adopt if we notice benefits due to shard awareness. I'm a bit confused as to which release to try. There is [3.7.2-scylla-2](https://github.com/scylladb/java-driver/releases/tag/3.7.1-scylla-2) (marked as "latest" by github); however there is also a 3.10.1-scylla-0 and 4.8.0-scylla-0 releases which appear as "latest" in the 3.x and 4.x series respectively on the [releases page](https://github.com/scylladb/java-driver/releases). Maybe I'm just having trouble interpretting the new Github UI. 

Any help would be greatly appreciated.

- JC

**Comment by haaawk** [comment]
3.10.1-scylla-0 and 4.8.0-scylla-0 are the ones to be used. I will switch latest to 3.10.1-scylla-0. Sorry for the confusion.

**Comment by haaawk** [comment]
3.10.1-scylla-0 and 4.8.0-scylla-0 are the ones to be used. I will switch
latest to 3.10.1-scylla-0. Sorry for the confusion.

**Comment by kharmabum** [comment]
@haaawk based on https://search.maven.org/search?q=com.scylladb `3.10.1-scylla-0` is the latest available for `scylla-driver-core` can you explain what `4.8.0-scylla-0` can/should be used for?

**Comment by haaawk** [comment]
Scylla driver is based on Cassandra's driver. Cassandra's driver has two incompatible lines: 3.x and 4.x
Scylla follows them. That's why there is 3.10.1-scylla for 3.x line and 4.8.0-scylla for 4.x line.

4.x is newer and better. For new projects, it's recommended to use it instead of 3.x

**Comment by kharmabum** [comment]
@haaawk thanks - very helpful.

**Comment by huiyongwang** [comment]
@haaawk So Scylla driver 4.x supports Shard-Aware feature and can connect the scylla specific port 19042, right?

**Comment by roydahan** [comment]
Yes

**Comment by huiyongwang** [comment]
A following question is: 
can scylla driver 4.x Shard-Aware feature work when I use it to connect to scylla specific port 19042 but the application is behind a NAT?

**Comment by mykaul** [comment]
@huiyongwang - nit: it's better to ask questions on our forum, users slack and/or users mailing list, then in Github issues.

**Comment by roydahan** [comment]
> A following question is: can scylla driver 4.x Shard-Aware feature work when I use it to connect to scylla specific port 19042 but the application is behind a NAT?

One small correction to my reply above, the 4.x is a shard-aware driver but it lacks the port 19042 which is a connection optimization.

Asking question is better at the community forum here: https://forum.scylladb.com/
