### ISSUE TITLE
4.x: Why Scylladb, doesn't support query and deletion of empty fields?

### ISSUE THREAD

**Issue by VolleyballBIA** [scylladb/java-driver#361]
I would like to report an issue on page https://java-driver.docs.scylladb.com/scylla-4.15.0.x/manual/query_builder/condition/index

### Problem
4.x: Why Scylladb, doesn't support query and deletion of empty fields? When I find abnormal data in my production environment, such as a non-indexed field that is empty, this creates a series of problems, then if I want to delete it, I have to do a full table scan to do so. I think this greatly affects the service performance.
Is there a good way to remove these empty data rows easily?

I have tried to remove them using Querybuilder and Cql and both failed.

###  Suggest a fix

**Comment by mykaul** [comment]
Questions are better asked on our forum - https://forum.scylladb.com/
