### ISSUE TITLE
Implement support for ALTER SESSION

### ISSUE THREAD

**Issue by haaawk** [scylladb/java-driver#48]
More details -> https://github.com/scylladb/scylla/pull/7617

**Comment by avelanarius** [comment]
Closing, as `ALTER SESSION` was ultimately not implemented in Scylla. The approach we took in Scylla was to use `USING TIMEOUT` and service-level timeouts, not anything that would alter a session. The only thing that could "alter" a session is `USE keyspace` which is already handled correctly by the driver.
