### ISSUE TITLE
Make sure docs work for each version/release of the driver

### ISSUE THREAD

**Issue by haaawk** [scylladb/java-driver#67]

**Comment by haaawk** [comment]
@lauranovich please comment on how we can enable sphinx for each branch/tag/release. Thanks.

**Comment by dgarcia360** [comment]
The tagged versions do not have the documentation generation system, which defines how docs should be built. To generate docs for these versions, we should add the ``docs`` folder from the latest branch to every affected branch. To make the process smoother, I've removed all the custom changes applied to the documentation pages in https://github.com/scylladb/java-driver/pull/74.

Then, we will be able to enable the documentation system for every affected branch following the next steps:

Let's say you want to generate docs for the version ``1.0-scylla``. You have already ported the custom ScyllaDB changes code and content changes (e.g. README) to the target branch, but you want to publish HTML docs for the new version.

1. Copy the ``docs`` directory from ``latest`` to the branch you want to enable docs generation. For our case, this would be a branch named ``1.0-scylla``. The directory contains the documentation generation system and how docs are structured.

2. Commit & push the copied files into the target branch. Make sure the docs build without errors:

```
cd docs
make preview
```

3. Move back to the ``latest`` branch. List the target version in ``docs/conf.py``.

```
.. code:: python
    BRANCHES = ['1.0-scylla']
    smv_branch_whitelist = multiversion_regex_builder(BRANCHES)
```

4. Commit & push the changes to the ``latest`` branch.

@haaawk @lauranovich @tzach Please let me know if you prefer me to submit the PRs for every branch (3.7.1-scylla, 3.9.0-scylla, 3.10.2-scylla, 4.8.0-scylla and 4.9.0-scylla) or if you prefer to do it with the instructions shared.

For future releases, [I still recommend adding custom changes (code and docs) in an integration branch (e.g. master) over cherry-picking custom changes on top of upstream updates](https://github.com/scylladb/java-driver/pull/38#issuecomment-702203297), in the same way other forked drivers are being maintained (python, cpp, gocqlx).

**Comment by tzach** [comment]
@haaawk @dgarcia360 how can we move forward with this?

**Comment by haaawk** [comment]
We are moving forward @tzach. I've rearranged 3.x branches to make them suitable for support of multiple documentation versions and @dgarcia360 is working on getting those versions up and running.
