### ISSUE TITLE
Docs: enforce https

### ISSUE THREAD

**Issue by tzach** [scylladb/java-driver#69]
The doc site already support https:
https://java-driver.docs.scylladb.com/latest/

But also work for http:
http://java-driver.docs.scylladb.com/latest/

There is a github option to enforce https
https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by tzach** [comment]
@haaawk can you add a doc tag?

**Comment by haaawk** [comment]
@tzach I added the label. Is that what you meant?

**Comment by tzach** [comment]
Yes, thanks (now we need to fix the issues ;)

**Comment by haaawk** [comment]
Done. The settings has been changed.
