### ISSUE TITLE
DOCS: Remove version number from the left menu

### ISSUE THREAD

**Issue by tzach** [scylladb/java-driver#76]
The list of version under change log on the left menu is confusing, make it look like doc versions
![image](https://user-images.githubusercontent.com/170200/110842109-5e6cac00-82af-11eb-8c3b-6fe0cb225d64.png)

I sugget to reduce the level of section headers in the changlog to remove it.

**Comment by avelanarius** [comment]
It's fixed now (did some cleanup of the branches in the driver repo).
