### ISSUE TITLE
README: invalid latest release number

### ISSUE THREAD

**Issue by avelanarius** [scylladb/java-driver#79]
In README on default branch (scylla-3.x), there are multiple mentions of `3.10.2.0` version ("If you're reading this on github.com" paragraph, Maven dependency in "Getting the driver", "Compatiblity" section). 

There is no `3.10.2.0` tag in repo and no `3.10.2.0` package in Maven (in this instance it should be `3.10.2-scylla-1`).

**Comment by haaawk** [comment]
Version is good. We just haven't released the right artefacts yet.
