### ISSUE TITLE
Add a Scylla fork to Maven 

### ISSUE THREAD

**Issue by tzach** [scylladb/java-driver#8]

**Comment by avnerbarr** [comment]
Any word on this?

**Comment by haaawk** [comment]
Our java driver has been published to Maven Central repository.
It can be accessed here: https://repo1.maven.org/maven2/com/scylladb/

Anyone can also use it by adding the following dependency to their pom.xml:

```
<dependency>
  <groupId>com.scylladb</groupId>
  <artifactId>scylla-driver-core</artifactId>
  <version>3.7.1-scylla-0</version>
</dependency>
```

or using a similar method for Ant, Gradle or SBT.

**Comment by avnerbarr** [comment]
is this release compatible with datastax 3.3 shaded?

**Comment by haaawk** [comment]
It's based on 3.7.1 release of Datastax driver.

**Comment by avnerbarr** [comment]
@haaawk @tzach  @slivne

Tested with Shlomi in one component and seems to behave well.

Next components will be a problem I suspect since they are relying on the shaded driver (conflict with Guava)

It would be great to publish the shaded version as well

**Comment by haaawk** [comment]
Shaded is there as well https://repo1.maven.org/maven2/com/scylladb/scylla-driver-core/3.7.1-scylla-0/scylla-driver-core-3.7.1-scylla-0-shaded.jar

**Comment by avnerbarr** [comment]
ah
great. I'll try that out.

**Comment by haaawk** [comment]
Try adding

` <classifier>shaded</classifier>`

**Comment by haaawk** [comment]
You may also need
```
<exclusions>
    <exclusion>
      <groupId>io.netty</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
```

But I'm not sure.
