### ISSUE TITLE
Shard-aware port (9042) implemented?

### ISSUE THREAD

**Issue by PeterCorless** [scylladb/java-driver#80]
Going over our driver coverage for a blog I am editing, I am looking for what issue to track for the Scylla-specific shard-aware port (9042) being implemented for our Java driver. If this is a duplicate, please point me to the right issue and close this, but a quick search for "shard-aware port" or "9042" did not reveal an issue # to me.

**Comment by haaawk** [comment]
I'm not aware of such issue. @PeterCorless please update the description of this issue to define what this task is about. It's missing the description of what port based shardawarness is.

**Comment by haaawk** [comment]
Shard-aware port has been implemented in Java driver for years. Closing.
