### ISSUE TITLE
Maven info for ScyllaDB driver fails

### ISSUE THREAD

**Issue by Laurent56** [scylladb/java-driver#81]
I am developing on a MacBook Pro, using:
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

When I used the Cassandra driver info, Maven works fine:
<dependency>
	<groupId>com.datastax.cassandra</groupId>
	<artifactId>cassandra-driver-core</artifactId>
	<version>3.0.1</version>
  </dependency>

However, when I try to use the ScyllaDB driver info:
<dependency>
  <groupId>com.scylladb</groupId>
  <artifactId>scylla-driver-core</artifactId>
  <version>3.10.2.0</version>
  </dependency>
I get this error: "Missing artifact: com.scylladb:scylla-driver-core:jar:3.10.2.0"
<img width="431" alt="Screen Shot 2021-05-03 at 4 02 15 PM" src="https://user-images.githubusercontent.com/6854269/116927035-1d4aa580-ac29-11eb-8024-a4d24b12cb75.png">

I need to use the ScyllaDB driver but am using C* Driver for the time being to make progress. Thanks.

**Comment by fggarcia** [comment]
@Laurent56 

https://mvnrepository.com/artifact/com.scylladb/scylla-driver-core

Actual version:
```
3.10.2-scylla-1
```

**Comment by Laurent56** [comment]
@fggarcia the ScyllaDB docs here: https://java-driver.docs.scylladb.com/stable/ should be updated then. Correct?

**Comment by fggarcia** [comment]
@Laurent56 i'm not a scylla developer :P 

@haaawk
