### ISSUE TITLE
DOCS: 404 errors 

### ISSUE THREAD

**Issue by lauranovich** [scylladb/java-driver#86]
Initially reported here https://github.com/scylladb/scylla-docs/issues/3656

From this page:
https://java-driver.docs.scylladb.com/stable/manual/statements/prepared/

Are the following Broken links:
PreparedStatement
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/PreparedStatement.html
BoundStatement
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/BoundStatement.html
setPrepareOnAllHosts
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/QueryOptions.html#setPrepareOnAllHosts-boolean-
setReprepareOnUp
https://java-driver.docs.scylladb.com/latest/api/com/datastax/driver/core/QueryOptions.html#setReprepareOnUp-boolean-

@haaawk - where should they link to?

**Comment by haaawk** [comment]
It seems that docs generation is wrong. The page is driver version dependant and the links are pointing to the "latest" branch while they should point to the branch that reflects the version picked from a dropbox in the upper left corner of the site. For example 3.10.2.x or 3.7.2.x.

When "latest" is replaced with a proper version in the link everything works:
https://java-driver.docs.scylladb.com/scylla-3.10.2.x/api/com/datastax/driver/core/QueryOptions.html#setReprepareOnUp-boolean-

**Comment by lauranovich** [comment]
we should have a latest branch, do we not?

**Comment by haaawk** [comment]
We do but it's no longer a default branch. scylla-3.x is the default branch now.

**Comment by lauranovich** [comment]
no what should be happening is the 3.x branch or whatever branch you specify is tagged as latest. Then, when you go to /latest you always get the most up to date official release. @dgarcia360 can assist in this matter

**Comment by haaawk** [comment]
I don't think that's correct. When a user selects a version from a drop down in the upper right corner, we should be linking to that version of the docs.

**Comment by lauranovich** [comment]
@haaawk they absolutely can do that - what the /latest helps us to do is not to maintain links. so If I click a link it will route me to latest. I understand that if I am in an old version this may be hard but I think there is a way to have the version inserted by the branch you're on - if this is what you want @dgarcia360 and I need to discuss how to implement

**Comment by haaawk** [comment]
Sure. If "latest" is what you prefer then "scylla-3.x" is the new latest

**Comment by lauranovich** [comment]
users will have the ability to choose the latest branch and the 3.whatever branch if the latest branch is 3.1 and a user chooses latest they will see the same content. - does this make sense?

**Comment by haaawk** [comment]
And "scylla-3.x" is exactly such branch. It's just not called "latest".

**Comment by avelanarius** [comment]
Fix merged: 1658c658b51780f7b601ce05f0aaa1137bd9d5e6
