### ISSUE TITLE
Optimize connection setup for shard aware driver

### ISSUE THREAD

**Issue by slivne** [scylladb/java-driver#9]
A clients that is using the shard-aware driver can better optimize the connection setup

Current algorithm is to iterate over the number of shards and connect to each. If the connection is setup to the non requested shard we drop the connection.

This can be optimized so on setup:
-  we create new connections 
-  created connection check to which shard it ends up 
    - if that shard does not have a connection - we use the new connection
    - if that shard has a connection we close the new connection
- we continue doing this till we have conenctions to all shards

**Comment by slivne** [comment]
@haaawk can you please comment on this

**Comment by haaawk** [comment]
Proposed optimization is the way driver works. I think this issue is wrongly assuming driver algorithm is inefficient.

**Comment by slivne** [comment]
Hm ... my bad - closing issue
